set_calibration:
  fields:
    entity_id:
      required: true
      example: "sensor.thermometer_temperature"
      selector:
        entity:
          filter:
            integration: tuya_local
    offset:
      required: true
      example: -0.4
      selector:
        number:
          min: -100
          max: 100
          step: 0.1
          mode: box
    attribute:
      example: "current_temperature"
      selector:
        text:
send_learned_ir_command:
  target:
    entity:
      domain: remote
      integration: tuya_local
  fields:
    command:
      required: true
      example: "Play"
      selector:
        object:
    device:
      example: "TV"
      selector:
        text:
    emitter_entity_id:
      example: "infrared.my_ir_emitter"
      required: true
      selector:
        entity:
          filter:
            domain: infrared
