name: Label PRs based on size

on: [pull_request_target]

jobs:
  add_pr_size_label:
    runs-on: ubuntu-latest
    name: Check PR size
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Fetch code
        uses: actions/checkout@v6
      - name: Label and comment PR
        uses: boschresearch/pr-size-labeler@v5
        # Uncomment these lines if you want to use your own custom configuration
        with:
          bucketConfigFile: .github/sizeBuckets.yml
